### ISSUE TITLE
Latest MarkLogic Java API

### ISSUE THREAD

**Issue by damonfeldman** [Pentaho-SE-EMEA-APAC/pdi-marklogic#5]
Great to see this, though I have not tried it yet! 

I recommend you upgrade to Java Client API 4.0-3.1 which fixes a bug in keeping all threads active, otherwise the issue can slow down operations.

**Comment by adamfowleruk** [comment]
Hi Damon!

Thanks for getting in touch. I'll quickly check this out. Just realised the client API is Apache 2 too, so I can actually distribute the JARs in our PDI plugin install package, so I'll make that change too.

If you give me a couple of days it'll be listed in the Pentaho Marketplace, making installation much easier.

**Comment by adamfowleruk** [comment]
Fixed in v1.0 release
